# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['pomodoro_timer.py'],
    pathex=[],
    binaries=[],
    datas=[('pomodoro_timer_icon.png', '.'), ('background.png', '.')],
    hiddenimports=[
        'tkinter',
        'pystray',
        'plyer',
        'PIL',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PomodoroTimer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesigning_identity=None,
    entitlements_file=None,
    icon='cinnamoroll_icon.ico',
)
